Fatal error: Class not found
The following error occurs when you click "publish" for a user subscription that has a subscription level with custom fields and is currently set to "enabled, no" 

Fatal error: Class 'Akeeba\Subscriptions\Admin\Controller\Inflector' not found in /administrator/components/com_akeebasubs/Controller/Subscriptions.php on line 42